"""Build the static site.

Copies site/ to dist/, replaces the {{SITE_URL}} token in text files with the
site_url from site.config.json, and generates sitemap.xml and robots.txt.

Usage: python -m site_tools.build [--site site] [--out dist] [--config site.config.json]
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parent.parent
TOKEN = "{{SITE_URL}}"
TEXT_SUFFIXES = {".html", ".xml", ".txt", ".json", ".webmanifest", ".svg", ".css", ".js"}
GENERATED_FILES = {"sitemap.xml", "robots.txt"}
NOT_IN_SITEMAP = {"404.html"}
NOINDEX_RE = re.compile(r"<meta\s+name=[\"']robots[\"'][^>]*content=[\"'][^\"']*noindex", re.IGNORECASE)


class BuildError(Exception):
    pass


def load_site_url(config_path: Path) -> str:
    config = json.loads(config_path.read_text(encoding="utf-8"))
    site_url = config.get("site_url", "")
    if not re.fullmatch(r"https://[a-z0-9.-]+(?::\d+)?/(?:[A-Za-z0-9._~-]+/)*", site_url):
        raise BuildError(f"site_url must be an https URL ending with '/', got {site_url!r}")
    return site_url


def last_modified(path: Path) -> str:
    """Date of the last commit touching `path`, else today (UTC)."""
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", str(path)],
            cwd=ROOT, capture_output=True, text=True, check=True,
        )
        if result.stdout.strip():
            return result.stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        pass
    return dt.datetime.now(dt.timezone.utc).date().isoformat()


def page_url(site_url: str, relative: PurePosixPath) -> str:
    if relative.name == "index.html":
        parent = relative.parent.as_posix()
        return site_url if parent == "." else f"{site_url}{parent}/"
    return f"{site_url}{relative.as_posix()}"


def render_sitemap(entries: list[tuple[str, str]]) -> str:
    urls = "".join(
        f"  <url>\n    <loc>{loc}</loc>\n    <lastmod>{lastmod}</lastmod>\n  </url>\n" for loc, lastmod in entries
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{urls}</urlset>\n"
    )


def render_robots(site_url: str) -> str:
    return f"User-agent: *\nAllow: /\n\nSitemap: {site_url}sitemap.xml\n"


def build(site_dir: Path, out_dir: Path, site_url: str) -> list[str]:
    """Build site_dir into out_dir. Returns the URLs written to the sitemap."""
    if not (site_dir / "index.html").is_file():
        raise BuildError(f"{site_dir}/index.html not found")
    for name in GENERATED_FILES:
        if (site_dir / name).exists():
            raise BuildError(f"{site_dir}/{name} must not exist: it is generated by the build")

    if out_dir.exists():
        shutil.rmtree(out_dir)
    shutil.copytree(site_dir, out_dir)

    sitemap: list[tuple[str, str]] = []
    for path in sorted(out_dir.rglob("*")):
        if not path.is_file() or path.suffix not in TEXT_SUFFIXES:
            continue
        text = path.read_text(encoding="utf-8").replace(TOKEN, site_url)
        if re.search(r"\{\{[A-Z_]+\}\}", text):
            raise BuildError(f"unresolved template token in {path.relative_to(out_dir)}")
        path.write_text(text, encoding="utf-8")

        relative = PurePosixPath(path.relative_to(out_dir).as_posix())
        if path.suffix == ".html" and relative.name not in NOT_IN_SITEMAP and not NOINDEX_RE.search(text):
            sitemap.append((page_url(site_url, relative), last_modified(site_dir / relative)))

    (out_dir / "sitemap.xml").write_text(render_sitemap(sitemap), encoding="utf-8")
    (out_dir / "robots.txt").write_text(render_robots(site_url), encoding="utf-8")
    return [loc for loc, _ in sitemap]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--site", type=Path, default=ROOT / "site")
    parser.add_argument("--out", type=Path, default=ROOT / "dist")
    parser.add_argument("--config", type=Path, default=ROOT / "site.config.json")
    args = parser.parse_args(argv)
    try:
        site_url = load_site_url(args.config)
        urls = build(args.site, args.out, site_url)
    except BuildError as error:
        print(f"build failed: {error}", file=sys.stderr)
        return 1
    print(f"Built {args.out} for {site_url} ({len(urls)} page(s) in sitemap)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
