import json
from pathlib import Path, PurePosixPath

import pytest

from site_tools.build import BuildError, build, load_site_url, page_url
from tests.conftest import SITE_URL


def test_build_resolves_tokens_and_generates_crawl_files(project: Path):
    dist = project / "dist"
    urls = build(project / "site", dist, SITE_URL)

    assert urls == [SITE_URL]  # 404.html is excluded
    html = (dist / "index.html").read_text(encoding="utf-8")
    assert "{{SITE_URL}}" not in html
    assert f'<link rel="canonical" href="{SITE_URL}">' in html
    assert f"<loc>{SITE_URL}</loc>" in (dist / "sitemap.xml").read_text(encoding="utf-8")
    assert (dist / "robots.txt").read_text(encoding="utf-8") == f"User-agent: *\nAllow: /\n\nSitemap: {SITE_URL}sitemap.xml\n"
    assert (dist / "assets" / "ahmed-abouseif-portrait.jpg").read_bytes() == (
        project / "site" / "assets" / "ahmed-abouseif-portrait.jpg"
    ).read_bytes()


def test_noindex_pages_stay_out_of_the_sitemap(project: Path):
    (project / "site" / "draft.html").write_text(
        '<html lang="en"><head><meta name="robots" content="noindex"></head><body></body></html>', encoding="utf-8"
    )
    (project / "site" / "ar").mkdir()
    (project / "site" / "ar" / "index.html").write_text('<html lang="ar"><head></head><body></body></html>', encoding="utf-8")
    assert build(project / "site", project / "dist", SITE_URL) == [f"{SITE_URL}ar/", SITE_URL]


def test_generated_files_must_not_exist_in_source(project: Path):
    (project / "site" / "robots.txt").write_text("User-agent: *\n", encoding="utf-8")
    with pytest.raises(BuildError, match="generated by the build"):
        build(project / "site", project / "dist", SITE_URL)


def test_unknown_template_tokens_fail_the_build(project: Path):
    (project / "site" / "extra.html").write_text("<p>{{SITE_NAME}}</p>", encoding="utf-8")
    with pytest.raises(BuildError, match="unresolved template token"):
        build(project / "site", project / "dist", SITE_URL)


@pytest.mark.parametrize("url", ["http://example.com/", "https://example.com", "https://Example.com/", "example.com/"])
def test_site_url_must_be_https_with_trailing_slash(tmp_path: Path, url: str):
    config = tmp_path / "site.config.json"
    config.write_text(json.dumps({"site_url": url}), encoding="utf-8")
    with pytest.raises(BuildError):
        load_site_url(config)


def test_repository_config_is_valid():
    assert load_site_url(Path(__file__).resolve().parent.parent / "site.config.json") == "https://ahmedabouseif.com/"


def test_page_url():
    assert page_url(SITE_URL, PurePosixPath("index.html")) == SITE_URL
    assert page_url(SITE_URL, PurePosixPath("ar/index.html")) == f"{SITE_URL}ar/"
    assert page_url(SITE_URL, PurePosixPath("cv.html")) == f"{SITE_URL}cv.html"
