from pathlib import Path

import pytest

from seo_agent.workspace import SiteWorkspace, ToolError
from tests.conftest import SITE_URL


@pytest.fixture
def ws(project: Path) -> SiteWorkspace:
    return SiteWorkspace(project, SITE_URL)


@pytest.mark.parametrize("path", ["../README.md", "/etc/passwd", "assets/../../secret.txt", "..\\x.html", ""])
def test_paths_outside_site_are_rejected(ws: SiteWorkspace, path: str):
    with pytest.raises(ToolError):
        ws.read_file(path)


def test_symlinks_are_rejected(ws: SiteWorkspace, project: Path):
    (project / "outside.txt").write_text("secret", encoding="utf-8")
    (project / "site" / "link.txt").symlink_to(project / "outside.txt")
    with pytest.raises(ToolError, match="outside site"):
        ws.read_file("link.txt")


def test_read_file_numbers_lines_and_supports_ranges(ws: SiteWorkspace):
    out = ws.read_file("index.html", 1, 2)
    assert out.splitlines()[1] == "    1\t<!doctype html>"
    assert "lines 1-2 of" in out.splitlines()[0]


def test_binary_files_cannot_be_read(ws: SiteWorkspace):
    with pytest.raises(ToolError, match="binary"):
        ws.read_file("assets/og-image.jpg")


def test_edit_requires_a_unique_exact_match(ws: SiteWorkspace, project: Path):
    with pytest.raises(ToolError, match="not found"):
        ws.edit_file("index.html", "this text is not in the page", "x")
    with pytest.raises(ToolError, match="occurs"):
        ws.edit_file("index.html", "<section", "<section ")
    with pytest.raises(ToolError, match="identical"):
        ws.edit_file("index.html", "<title>", "<title>")

    ws.edit_file("index.html", "<title>Ahmed Abouseif — Executive Portfolio</title>", "<title>New title</title>")
    assert "<title>New title</title>" in (project / "site" / "index.html").read_text(encoding="utf-8")


def test_create_file_rules(ws: SiteWorkspace, project: Path):
    with pytest.raises(ToolError, match="already exists"):
        ws.create_file("index.html", "x")
    with pytest.raises(ToolError, match="generated by the build"):
        ws.create_file("robots.txt", "User-agent: *")
    with pytest.raises(ToolError, match="can be created"):
        ws.create_file("script.py", "print(1)")

    ws.create_file("notes/about.txt", "hello")
    assert (project / "site" / "notes" / "about.txt").read_text(encoding="utf-8") == "hello"


def test_fetch_is_limited_to_the_site_hosts(ws: SiteWorkspace):
    assert ws.allowed_hosts == {"example.com", "www.example.com"}
    for url in ["https://evil.example.org/", "file:///etc/passwd", "ftp://example.com/", "http://169.254.169.254/"]:
        with pytest.raises(ToolError):
            ws.fetch_live(url)


def test_snapshot_detects_changes(ws: SiteWorkspace):
    before = ws.snapshot()
    ws.edit_file("index.html", "<title>Ahmed Abouseif — Executive Portfolio</title>", "<title>Changed</title>")
    after = ws.snapshot()
    assert [p for p in after if after[p] != before[p]] == ["index.html"]
